<?php
?>
<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list">
    <li>
        <div class="atos-logo">
            <?php foreach ($this->getCreditCardsAccepted() as $card): ?>
                <?php $cbLogo = "Ynote_Lydia::logo/" . $card . ".gif"; ?>
                <img src="<?php echo $this->getViewFileUrl($cbLogo); ?>" alt="<?php echo $card ?>" />
            <?php endforeach; ?>
        </div>
    </li>
</ul>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
    <li><?php echo $this->__('You will be redirected to the payment server after the finalization of your order.') ?></li>
</ul>
